<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	<OutputType>Exe</OutputType>
	<RootNamespace>CSM_System_Database_Testing</RootNamespace>
	<PackageId>CSM.System.Database.Testing</PackageId>
	<Version>1.0.0</Version>
	<Authors>Erick Ponciano</Authors>
	<Company>Cosmos (CSM)</Company>
	<RepositoryUrl>https://github.com/Cosmos-CSM/csm_system_database</RepositoryUrl>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<PackageReadmeFile>CHANGELOG.md</PackageReadmeFile>
	<IsPackable>true</IsPackable>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CSM.Database.Testing" Version="8.0.0" />
	<PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSM System Database Core\CSM System Database Core.csproj" />
  </ItemGroup>
	
  <ItemGroup>
    <None Include="CHANGELOG.md" Pack="true" PackagePath="" />
  </ItemGroup>


  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>